sudo: required
language: generic

services:
  - docker

env:
  global:
    - BUILDER_VERSION_PREFIX: 0.0
    - TILE_VERSION: 0.0.1

before_install:
  - git submodule update --recursive --init

script:
  - docker build -t p-weave-builder .
  - docker run -v $(pwd):/work -ti p-weave-builder $TILE_VERSION

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
    docker tag p-weave-builder weaveworks/p-weave-builder:${BUILDER_VERSION_PREFIX}.${TRAVIS_BUILD_NUMBER};
    docker push weaveworks/p-weave-builder:${BUILDER_VERSION_PREFIX}.${TRAVIS_BUILD_NUMBER};
    fi
